sudo: required
services:
  - docker

before_install:
  - docker build -t ganeshchandran/docker-react -f Dockerfile.dev .

script:
  - docker run ganeshchandran/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "web02"
  env: "web02-env"
  bucket_name: "elasticbeanstalk-ap-south-1-204532264550"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

